### ISSUE TITLE
Local variable declaration does not respect scoping

### ISSUE THREAD

**Issue by ellliottt** [vktec/c4#12] opened 2020-11-11 18:15 UTC
**What went wrong?**

Defining two variables of the same name in different scopes incorrectly errors with `Variable already exists`.

**What caused it?**

```c
fn a() Void {
    var x I32
}

fn b() Void {
    var x I32
}
```

**Comment by vktec** [comment] 2020-11-11 18:16
Duplicate of #11, but that one is less detailed 'cause I'm lazy so I'll close that instead

**Closed** 2020-11-13 00:54 UTC
Labels: bug
